### PR TITLE
reflect click event of checkbox on search filter

### LINKED ISSUE #849: Category check mark not checked during session search
**Describe the bug**
Tapping the name of a category during a session search turns on the checkbox, but tapping the checkbox itself does not turn on the checkbox.

**To Reproduce**
1. Go to 'Search'
2. Click on 'Category'
3. Tap the checkbox
4. The checkbox is not checked.

**Expected behavior**
Tap the checkbox itself to check the box.

**Screenshots**

https://user-images.githubusercontent.com/51113946/194061041-4e32d036-e702-4858-b427-a06a7bafacfc.mp4

### PR DESCRIPTION
**Pull request by ked4ma**
## Issue
- close #849

## Overview (Required)
- On search filter, click event of checkboxes weren't dealt
- enable to toggle filters by also tapping checkboxes themselves
- I noticed that Day Filter has same issue, so I modified both filters (day/category)

## Links
- [App Design](https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1)
- [Accessibility in Compose](https://developer.android.com/jetpack/compose/accessibility)

## Screenshot
Before | After
:--: | :--:
<video src="https://user-images.githubusercontent.com/74723074/194279565-a793dd60-db29-4a0c-be9d-6fc42e886ddd.mp4" type="video/mp4" /> | <video src="https://user-images.githubusercontent.com/74723074/194279590-071bfbe0-9047-4d39-8398-fa871a54a836.mp4" type="video/mp4" />
<video src="https://user-images.githubusercontent.com/74723074/194279803-c1f68cee-75ac-4f3a-b725-1dbde489f794.mp4" type="video/mp4" /> | <video src="https://user-images.githubusercontent.com/74723074/194279829-1a70399a-2b63-49d3-afb6-7896c5b57ac2.mp4" type="video/mp4" />

### CODE REVIEW

**Comment by takahirom** [comment]
👀

File: feature/sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/SearchFilterSheets.kt [hunk 1]
```diff
@@ -85,7 +87,9 @@ fun FilterDaySheet(
 
                 Checkbox(
                     checked = selectedDays.contains(kaigiDay),
-                    onCheckedChange = {},
+                    onCheckedChange = null,
+                    modifier = Modifier
+                        .size(LocalViewConfiguration.current.minimumTouchTargetSize),
```
Comment (takahirom) [inline feature/sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/SearchFilterSheets.kt:92]: I didn't know about LocalViewConfiguration! Thanks
