### PR TITLE
fix composeLint

### LINKED ISSUE #409: Run "./gradlew composeLint" and fix errors
**Idea Description**
The title says everything.
Errors are unused variables, etc. There are not that many.

**Reference images and links**

### PR DESCRIPTION
**Pull request by iwata-n**
## Issue
- close #409

## Overview (Required)
- remove unused test
- comment out unused parameters

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

File: feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/Hours.kt [hunk 1]
```diff
@@ -226,10 +226,10 @@ private fun itemProvider(
 private val lineStrokeSize = 1.dp
 private val horizontalLineTopOffset = 48.dp
 private val hoursWidth = 75.dp
-private val hoursItemWidth = 43.dp
-private val hoursItemHeight = 24.dp
+// private val hoursItemWidth = 43.dp // TODO unused property
```
Comment (takahirom) [inline feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/Hours.kt:229]: I think we can delete these variables. 🙏

**Review by takahirom — APPROVED** [review]
Thanks to you, our application will be supported by automation!
