### PR TITLE
:recycle: Update Handle multiple URL in announcement

### LINKED ISSUE #721: Handle multiple URL in announcement
**Idea Description**
Current implementation always uses the first URL in announcement. So If we have multiple URLs in the announcement, it does not work.
https://github.com/DroidKaigi/conference-app-2022/pull/719

**Reference images and links**
https://twitter.com/Fumiya_Kume/status/1573523409707085824

### PR DESCRIPTION
**Pull request by Corvus400**
## Issue
- close #721 

## Overview (Required)
- As the title says.
- I'd like to put the same process in the session details screen, so I'll deal with it later.

## Links
- Nothing.

## Movie

https://user-images.githubusercontent.com/13657682/192342380-cfabb87b-4624-4b8e-81ee-7ea1d82d95fb.mp4

https://user-images.githubusercontent.com/13657682/192342405-d4c2dd5b-9d55-494c-a0f7-88e41865b476.mp4

https://user-images.githubusercontent.com/13657682/192342442-3fcb7598-4434-4070-b641-cd0e6fcad36d.mp4

after2

### CODE REVIEW

File: feature/announcement/src/main/java/io/github/droidkaigi/confsched2022/feature/announcement/Announcements.kt [hunk 1]
```diff
@@ -189,15 +192,43 @@ fun AnnouncementContent(
...
 
-    Column(
-        modifier = Modifier.clickable {
-            regex.find(content)?.let {
-                onLinkClick(it.value)
-            }
-        },
-    ) {
+        var lastIndex = 0
+        urlRegex.findAll(content).forEach { matchResult ->
```
Comment (takahirom) [inline feature/announcement/src/main/java/io/github/droidkaigi/confsched2022/feature/announcement/Announcements.kt:206]: How about memorizing?

```kotlin
val findedUrlResults = remember(content) {
  urlRegex.findAll(content)
}
val annotatedString = buildAnnotatedString {
...
```

**Review by takahirom — APPROVED** [review]
This is a very useful implementation!
