### PR TITLE
:wrench: Fix Allow speakers to display again.

### LINKED ISSUE #365: Session speakers are not shown
**Describe the bug**
Session speakers are not shown.

It looks like SessionDao is not storing session speakers in DB.
https://github.com/DroidKaigi/conference-app-2022/blob/main/core-data/src/commonMain/kotlin/io/github/droidkaigi/confsched2022/data/sessions/SessionsDao.kt#L60-L62

**To Reproduce**
1. Go to any session detail screen
2. Always speakers are not shown

**Expected behavior**
Speakers are shown.

**Screenshots**

### PR DESCRIPTION
**Pull request by Corvus400**
## Issue
- close #365 

## Overview (Required)
- Created an intermediate table because there are many-to-many speakers and sessions.
- Changed timetableItemId to id.
- It is working, but I am not sure if this is the right thing to do... 😓

## Links
- Nothing.

## Movie

https://user-images.githubusercontent.com/13657682/189592094-edf7d54e-f6ee-4e3f-a65b-6b1a69a26b13.mp4

https://user-images.githubusercontent.com/13657682/189592135-3f98e3a0-10d6-4807-a99f-3e117d49c29f.mp4

### CODE REVIEW

File: core-data/src/commonMain/kotlin/io/github/droidkaigi/confsched2022/data/sessions/SessionsDao.kt [hunk 1]
```diff
@@ -55,16 +57,33 @@ class SessionsDao(
...
+                    timetableItem.speakers.forEach { speaker ->
+                        val timetableItemSpeaker = TimetableItemSpeaker(
+                            id = speaker.id,
+                            name = speaker.name,
+                            iconUrl = speaker.iconUrl,
+                            bio = speaker.bio,
+                            tagLine = speaker.tagLine,
+                        )
+                        val timetableItemSessionSpeakers = TimetableItemSessionSpeakers(
+                            id = index.toLong(),
```
Comment (Corvus400) [inline core-data/src/commonMain/kotlin/io/github/droidkaigi/confsched2022/data/sessions/SessionsDao.kt:73]: I would like to avoid having to set id. 🤔

File: core-data/src/commonMain/sqldelight/io/github/droidkaigi/confsched2022/data/TimetableItemSessionSpeakers.sq [hunk 2]
```diff
@@ -0,0 +1,24 @@
+CREATE TABLE timetableItemSessionSpeakers (
```
Comment (Corvus400) [inline core-data/src/commonMain/sqldelight/io/github/droidkaigi/confsched2022/data/TimetableItemSessionSpeakers.sq:1]: Can we have better names for the intermediate tables?🤔

File: core-data/src/commonMain/kotlin/io/github/droidkaigi/confsched2022/data/sessions/SessionsDao.kt [hunk 3]
```diff
@@ -130,11 +150,11 @@ class SessionsDao(
...
 
-    private fun List<TimetableItemSession>.mapToSessionList(
-        timetableItemSpeakers: List<TimetableItemSpeaker>,
-    ): List<TimetableItem.Session> {
+    private fun List<TimetableItemSession>.mapToSessionList(): List<TimetableItem.Session> {
         return map { session ->
-            val speakers = timetableItemSpeakers.filter { it.timetableItemId == session.id }
+            val speakers = timetableItemSessionSpeakersQueries
+                .selectSpeakers(session.id)
+                .executeAsList()
```
Comment (Corvus400) [inline core-data/src/commonMain/kotlin/io/github/droidkaigi/confsched2022/data/sessions/SessionsDao.kt:157]: Is this process ok here? 🤔

File: core-data/src/commonMain/sqldelight/io/github/droidkaigi/confsched2022/data/TimetableItemSpeaker.sq [hunk 4]
```diff
@@ -1,20 +1,20 @@
...
 FROM timetableItemSpeaker;
 
 insert:
-INSERT INTO timetableItemSpeaker (
-    timetableItemId,
+INSERT OR IGNORE INTO timetableItemSpeaker (
+    id,
     name,
     iconUrl,
     bio,
```
Comment (takahirom) [inline core-data/src/commonMain/sqldelight/io/github/droidkaigi/confsched2022/data/TimetableItemSpeaker.sq:20]: Does our application need migration? Can you implement this?
https://github.com/DroidKaigi/conference-app-2021/blob/23517099f70ce39c92202df4c9fd208f7740ce56/data/db/src/commonMain/kotlin/io/github/droidkaigi/feeder/data/DestructiveMigrationSchema.kt#L6

File: core-data/src/commonMain/sqldelight/io/github/droidkaigi/confsched2022/data/TimetableItemSessionSpeakers.sq (hunk 2 above)
Comment (takahirom) [reply core-data/src/commonMain/sqldelight/io/github/droidkaigi/confsched2022/data/TimetableItemSessionSpeakers.sq:1]: How about "TimetableItemSpeakerCrossRef" from
https://developer.android.com/training/data-storage/room/relationships#many-to-many

File: core-data/src/commonMain/kotlin/io/github/droidkaigi/confsched2022/data/sessions/SessionsDao.kt (hunk 3 above)
Comment (takahirom) [reply core-data/src/commonMain/kotlin/io/github/droidkaigi/confsched2022/data/sessions/SessionsDao.kt:157]: This is DAO. So I think OK.

**Review by takahirom — APPROVED** [review]
Totally great! We need this implementation definitely!

File: core-data/src/androidMain/kotlin/io/github/droidkaigi/confsched2022/data/DriverFactory.kt [hunk 5]
```diff
@@ -0,0 +1,11 @@
+package io.github.droidkaigi.confsched2022.data
+
+import android.content.Context
+import com.squareup.sqldelight.android.AndroidSqliteDriver
+import com.squareup.sqldelight.db.SqlDriver
+
+actual class DriverFactory(private val context: Context) {
```
Comment (takahirom) [inline core-data/src/androidMain/kotlin/io/github/droidkaigi/confsched2022/data/DriverFactory.kt:7]: I'd say we need to use an interface instead of "expect actual" .
https://github.com/DroidKaigi/conference-app-2022/pull/286#issuecomment-1240914531
e: /Users/runner/work/conference-app-2022/conference-app-2022/core-data/src/commonMain/kotlin/io/github/droidkaigi/confsched2022/data/DriverFactory.kt: (5, 14): Expected class 'DriverFactory' has no actual declaration in module <core-data_debug> for JVM
> Task :core-data:compileDebugUnitTestKotlinAndroid FAILED

**Comment by Corvus400** [comment]
@takahirom 
I could fix it, please re-review!🙏
